### ISSUE TITLE
Add check-all pre-commit hook 

### ISSUE THREAD

**Issue by Cedric-Magnan** [artefactory/pre-commit-dbt#9]
**Describe the feature you'd like**

Add a pre-commit hook that runs all recommended pre-commit hooks with default recommended values :
repos:
```yaml
- repo: https://github.com/artefactory/pre-commit-dbt
  rev: v1.0.0
  hooks:
  - id: check-all
```
